## This is a sample values yamls for usage with 
##   venonactl install agent|runtime|monitor --values|-f values.yaml
##

## the values from values.yaml are applied to the templates in [pkg/templates/kubernetes](pkg/templates/kubernetes)
## See BuildValues() func in [store.go](pkg/store/store.go) for the format 

# Codefresh host --api-host and token --api-token
CodefreshHost: https://my-codefresh.example.com
Token:         xxxxx.yyyyyyyy

# Runner:
#   Limits:
#     CPU: 400m
#     Memory: 1200Mi
#   Requests:
#     CPU: 200m
#     Memory: 500Mi

# Runner (venona) image 
Image: 
  Name: codefresh/venona
  Tag: 1.4.16 # default s.Version.Current.Version,

## Namespace - from --kube-namespace parameter + env KUBE_NAMESPACE, for venona, runtime, monitor
Namespace: r1
### ConfigPath - kubeconfig from --kube-config-path
#ConfigPath: 
## Context: from both --context (global arg) and 
#Context: gke_codefresh_cluster

### NodeSelector --kube-node-selector
#NodeSelector: app_type=codefresh,cloud.google.com/gke-nodepool=default-pool

### --tolerations
# Tolerations: 
# - key: codefresh.io
#   operator: Equal
#   value: dinds
#   effect: NoSchedule

## --docker-registry
# DockerRegistry:    s.DockerRegistry,

### AdditionalEnvVars - for runner deployment, coming from --envVars param
### Example for setting proxy
# AdditionalEnvVars:
#   HTTP_PROXY: 10.20.0.35:8080
#   HTTPS_PROXY: 10.20.0.35:8080
#   NO_PROXY: 10.20.0.*,

### RuntimeEnvironmentName: my-unique-runtime-name
# RuntimeEnvironmentName: my-unique-runtime-name

### RuntimeServiceAccount For venonactl attach
# RuntimeServiceAccount:

### use InsecureSkipVerify to call cf api
#insecure: true

### Use already existing storage class
#StorageClass: 

### AgentToken:        s.AgentAPI.Token,
### AgentId:           s.AgentAPI.Id,
# AgentId: gke_codefresh-load_us-central1-c_onprem-tst-1_r1_6

### Storage parameters - for dind-volume-provisoner
# Storage:
#   Backend: local
#   StorageClassName:     
#   LocalVolumeParentDir: /var/lib/codefresh/dind-volumes
#   AvailabilityZone: 
#   GoogleServiceAccount: 
#   AwsAccessKeyId: 
#   AwsSecretAccessKey: 
#   VolumeProvisioner:
#     Image: codefresh/dind-volume-provisioner:v23
#     NodeSelector: 
#     Tolerations:
#     Limits:
#       CPU: 400m
#       Memory: 1200Mi
#     Requests:
#       CPU: 200m
#       Memory: 500Mi 
#   LocalVolumeMonitor: 
#     Limits:
#        CPU: 400m
#        Memory: 1200Mi
#     Requests:
#        CPU: 200m
#        Memory: 500Mi  


### Storage parameters example for gke-local-ssd
# Storage:
#   Backend: local
#   LocalVolumeParentDir: /mnt/disks/ssd0/codefresh-volumes 
# NodeSelector: cloud.google.com/gke-local-ssd=true 

### Storage parameter example for gke disks
# Storage:
#   Backend: gcedisk
#   AvailabilityZone: us-central1-a
#   GoogleServiceAccount: >
#     {serviceAccount.json context}
# NodeSelector: failure-domain.beta.kubernetes.io/zone=us-central1-a

### Storage parameter example for aws ebs disks
# Storage:
#   Backend: ebs
#   AvailabilityZone: us-east-1d
#   AwsAccessKeyId: ABCDF
#   AwsSecretAccessKey: ZYXWV
#   VolumeProvisioner: 
#     NodeSelector: kubernetes.io/role=master
# NodeSelector: failure-domain.beta.kubernetes.io/zone=us-east-1d

# Monitor:
#   UseNamespaceWithRole: s.UseNamespaceWithRole
#   RbacEnabled: true,
#   Helm3:       s.Helm3,
#   AppName:     MonitorApplicationName,
#   Image:
#     Name: codefresh/agent,
#     Tag:  stable,
