apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .AppName }}
    version: {{ .Version }} 
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .AppName }}
      version: {{ .Version }}
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .AppName }}
        version: {{ .Version }}
    spec:
      volumes:
        - name: runnerconf
          secret:
            secretName: runnerconf
      {{ if ne .NodeSelector "" }}
      nodeSelector:
{{ .NodeSelector | nodeSelectorParamToYaml | indent 8 | unescape }}
      {{ end }}
      {{ if ne .Tolerations "" }}
      tolerations:
        {{ .Tolerations | indent 8 }}
      {{ end }}
      containers:
      - env:
        {{- if $.AdditionalEnvVars }}
        {{- range $key, $value := $.AdditionalEnvVars }}
        - name: {{ $key }}
          value: "{{ $value}}"
        {{- end}}
        {{- end}}
        - name: SELF_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CODEFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .AppName }}
              key: codefresh.token
        - name: CODEFRESH_HOST
          value: {{ .CodefreshHost }}
        - name: AGENT_MODE
          value: {{ .Mode }}
        - name: AGENT_NAME
          value: {{ .AppName }}
        - name: "AGENT_ID"
          value: {{ .AgentId }}
        - name: VENONA_CONFIG_DIR
          value: "/etc/secrets"
        image: {{ .Image.Name }}:{{ .Image.Tag }}
        volumeMounts:
        - name: runnerconf
          mountPath: "/etc/secrets"
          readOnly: true
        imagePullPolicy: Always
        name: {{ .AppName }}
      restartPolicy: Always
