apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: {{ .AppName }}
  template:
    metadata:
      labels:
        app: {{ .AppName }}
        version: {{ .Version }}
    spec:
      {{- if .Monitor.RbacEnabled}}
      serviceAccountName: {{ .AppName }}
      {{- end }}
      containers:
      - name: {{ .AppName }}
        image: "{{ .Image.Name }}:{{ .Image.Tag }}"
        imagePullPolicy: Always
        env:
          - name: SERVICE_NAME
            value: {{ .AppName }}
          {{- if .Monitor.UseNamespaceWithRole }}
          - name: ROLE_BINDING
            value: "true"
          {{- end }}
          - name: PORT
            value: "9020"
          - name: API_TOKEN
            value: {{ .Token }}
          - name: CLUSTER_ID
            value: {{ .ClusterId }}
          - name: API_URL
            value: {{ .CodefreshHost }}/api/k8s-monitor/events
          - name: ACCOUNT_ID
            value: user
          - name: HELM3
            value: "{{ .Monitor.Helm3 }}"
          - name: NAMESPACE
            value: "{{ .Namespace }}"
          - name: NODE_OPTIONS
            value: "--max_old_space_size=4096"
        ports:
        - containerPort: 9020
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 9020
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
