# used by:
# - monitor pod
{{- if .CreateRbac }}
{{- if and .Monitor.RbacEnabled (not .Monitor.UseNamespaceWithRole) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Monitor.AppName }}-rollback
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Monitor.AppName }}
    version: {{ .Version }}
{{- end }}
{{- end }}