# used by:
# - app-proxy pod
{{- if .CreateRbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .AppProxy.AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppProxy.AppName }}
    version: {{ .Version }}
{{- end }}
